version: "3.9"

services:
  simstudio:
    image: ghcr.io/itsmenavi38123/simstudio:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./apps/sim/.env
    depends_on:
      - migrations
      - realtime
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:3000"]
      interval: 90s
      timeout: 5s
      retries: 3
      start_period: 10s

  realtime:
    image: ghcr.io/itsmenavi38123/realtime:latest
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./apps/sim/.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:3002/health"]
      interval: 90s
      timeout: 5s
      retries: 3
      start_period: 10s

  migrations:
    image: ghcr.io/itsmenavi38123/migrations:latest
    env_file:
      - ./apps/sim/.env
    command: ["bun", "run", "db:migrate"]
    restart: "no"
